"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""
import unittest

from utils.math.seqs.seq_fibonacci import SeqFibonacci

def euler_002(limit):
	fibonacci = SeqFibonacci().get_list(max_val=limit - 1)
	return sum(n for n in fibonacci if n % 2 == 0)

class Test(unittest.TestCase):
	def test(self):
		self.assertEquals(euler_002(limit=4000000), 4613732)
